// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBommyAn5PZ0g0MusBwrRAe8SpT6KIpzTM',
    appId: '1:289528738611:web:8eb5511a445bb45b924446',
    messagingSenderId: '289528738611',
    projectId: 'sment-bottle-crud',
    authDomain: 'sment-bottle-crud.firebaseapp.com',
    storageBucket: 'sment-bottle-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG_VorGfoQqO9an_uJohwV_OmxYaI4D70',
    appId: '1:289528738611:android:600737d36f196b2b924446',
    messagingSenderId: '289528738611',
    projectId: 'sment-bottle-crud',
    storageBucket: 'sment-bottle-crud.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBommyAn5PZ0g0MusBwrRAe8SpT6KIpzTM',
    appId: '1:289528738611:web:951568160d6cb96f924446',
    messagingSenderId: '289528738611',
    projectId: 'sment-bottle-crud',
    authDomain: 'sment-bottle-crud.firebaseapp.com',
    storageBucket: 'sment-bottle-crud.appspot.com',
  );
}
